name: "Prepare Dependencies"
description: "Prepares all Node and PNPM dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24.x"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Sync Svelte
      shell: bash
      run: pnpm run sync
