name: "Check pull request"

on: pull_request

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check formatting with Prettier
        run: pnpm turbo run format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Lint
        run: pnpm turbo run lint

  type-check:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check TypeScript Types
        run: pnpm turbo run type-check

  check-svelte:
    name: Check Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check Svelte
        run: pnpm turbo run svelte-check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Cache playwright binaries
        uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: cache-playwright-linux-1.22.2
      - name: Install Playwright Dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm playwright install-deps chromium
      - name: Test
        run: pnpm turbo run test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Build
        run: pnpm turbo run build
