name: "Check pull request"

on: pull_request

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check formatting with Prettier
        run: pnpm turbo run check:format

  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check Lint
        run: pnpm turbo run check:lint

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check TypeScript Types
        run: pnpm turbo run check:ts

  check-svelte:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Check Svelte
        run: pnpm turbo run check:svelte

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Test
        run: pnpm turbo run check:test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Build
        run: pnpm turbo run build
