name: "Check pull request"

on: pull_request

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-deps

      - name: Check formatting with Prettier
        run: pnpm turbo run format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-deps

      - name: Lint
        run: pnpm turbo run lint

  check-svelte:
    name: Check Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-deps

      - name: Check Svelte
        run: pnpm turbo run svelte-check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-deps

      - name: Build
        run: pnpm turbo run build
