name: Deploy to Deno Deploy
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Build
        run: pnpm turbo run build

      - name: Upload to Deno Deploy
        id: deployment
        uses: denoland/deployctl@v1
        with:
          project: "reinhold-is"
          root: "./dist"
          entrypoint: "./server/entry.mjs"

      - name: Comment with Deployment URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            # Deploy Preview
            Deploy preview ready at [${{ steps.deployment.url }}](${{ steps.deployment.url }})
