name: Deploy to Deno Deploy
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-deps

      - name: Build
        run: pnpm turbo build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "reinhold-is"
          entrypoint: "./dist/server/entry.mjs"
