name: Monitor Cloudflare Pages Deployment
on:
  push:

jobs:
  monitor-deployment:
    name: Monitor Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Wait for Cloudflare Pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN  }}
          accountId: "d794f21cf51366d71691241a5deb1eef"
          project: "reinhold-is"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
